name: CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
  
      - name: Decode google-services.json
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        run: echo "$FIREBASE_SECRET" > ./app/google-services.json

      - name: Decode fcm.json
        env:
          FIREBASE_SECRET_PUSHER: ${{ secrets.FIREBASE_SECRET_PUSHER }}
        run: |
          mkdir -p ./pusher
          echo "$FIREBASE_SECRET_PUSHER" > ./pusher/fcm.json

      - name: Build Android
        run: |
          chmod +x ./gradlew
          ./gradlew :app:assembleDebug

      - name: Build Pusher
        run: ./gradlew :pusher:build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk


